(deftheme my-dark-theme
  "Created 2025-11-05.")

(custom-theme-set-faces
 'my-dark-theme
 '(default ((t (:family "Adwaita Mono" :foundry "UKWN" :width normal :height 113 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ffffff" :background "#000000" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ffffff"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#ff5f59"))))
 '(homoglyph ((t (:foreground "#fec43f"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:foreground "#ffffff" :background "#45605e"))))
 '(region ((t (:extend t :foreground "#ffffff" :background "#5a5a5a"))))
 '(shadow ((t (:foreground "#989898"))))
 '(secondary-selection ((t (:extend t :foreground "#ffffff" :background "#654a39"))))
 '(trailing-whitespace ((t (:background "#9d1f1f"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#f78fe7" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#989898" :inherit (modus-themes-slant)))))
 '(font-lock-constant-face ((t (:foreground "#00bcff"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#9ac8e0" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#caa6df" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#feacd0"))))
 '(font-lock-keyword-face ((t (:foreground "#b6a0ff" :inherit (modus-themes-bold)))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#ff7f9f"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#feacd0" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00c06f" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#79a8ff"))))
 '(font-lock-type-face ((t (:foreground "#6ae4b9" :inherit (modus-themes-bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#00d3d0"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#fec43f" :inherit (modus-themes-bold)))))
 '(button ((t (:underline (:color "#79a8ff" :style line :position nil) :foreground "#79a8ff"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:underline (:color "#feacd0" :style line :position nil) :foreground "#feacd0"))))
 '(fringe ((t (:foreground "#ffffff" :background "#1e1e1e"))))
 '(header-line ((t (:background "#1e1e1e" :inherit (modus-themes-ui-variable-pitch)))))
 '(tooltip ((t (:foreground "#ffffff" :background "#535353"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#959595" :style nil) :foreground "#ffffff" :background "#505050" :inherit (modus-themes-ui-variable-pitch)))))
 '(mode-line-buffer-id ((t (:inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#9fefff" :inherit (bold)))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#ffffff" :style nil) :foreground "#ffffff" :background "#45605e"))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#606060" :style nil) :foreground "#969696" :background "#2d2d2d" :inherit (modus-themes-ui-variable-pitch)))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#ffffff" :background "#552f5f"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace))))))

(provide-theme 'my-dark-theme)
